force_cast: error
force_try: error

# disabled temporarily
# included:
# - BottomSheetPresenter/Lib

excluded:
  - Carthage

line_length:
  warning: 110
  error: 120

identifier_name:
  min_length: 1
